### ISSUE TITLE
Investigate compat with f4

### ISSUE THREAD

**Issue by mck1117** [mck1117/proteus#10]
How much has to change to also support the lqfp144 `STM32F407ZG`?

**Comment by mck1117** [comment]
A first glance suggests that the pinout of of the `F767ZI` is identical to that of the `F407ZG`

**Comment by mck1117** [comment]
The STM32F412 and STM32F767 nucleo boards use the same board, with a different chip installed, which suggests compatibility as well.

**Comment by 960** [comment]
I have used the F407 and F767 at the same boards all along, so I know for sure they are 100% compatible

**Comment by mck1117** [comment]
Cool - between those data points, I think we're all set here.
