### ISSUE TITLE
Schematics note which diodes are usually populated which ones are not

### ISSUE THREAD

**Issue by rusefillc** [mck1117/proteus#104]
Schematics shows

![image](https://user-images.githubusercontent.com/48498823/135719055-2aaea206-ffef-4594-92be-d861d9b5fc10.png)

looking it seem like proteus has 4 diodes. In reality two diodes on top side D102 D104 are always populated while two diodes on the back D101, D103 are pretty much always NOT populated

let's a have a note of that on the schematics?

**Comment by rusefillc** [comment]
also text all over text is an eye sore

**Comment by mck1117** [comment]
![image](https://user-images.githubusercontent.com/568254/161406062-b7312dd9-9adb-44f3-b164-212a844c01e5.png)

What if we just fit all 4 instead :)

**Comment by rusefillc** [comment]
off topic: 

I have sad news for you RE

![image](https://user-images.githubusercontent.com/48498823/161406146-0896bb2a-d9b6-4f24-9bd3-0e19fc2dd6d6.png)
