### ISSUE TITLE
0.4 unit not powering up from +12v IGN

### ISSUE THREAD

**Issue by rusefillc** [mck1117/proteus#105]
I believe I have a damaged Proteus 0.4 board

I apply +12v on IGN pin 18, I have GND and I do not get +5

@qwerty-off suggested that I check voltage on the huge diode (?)

I have +12 on one side of huge D but not on the other

![image](https://user-images.githubusercontent.com/48498823/139598113-907e52b4-3203-400f-8cd6-9ed3f35b133c.png)

do we suspect damaged huge D? how would that happen?

**Comment by Qwerty-OFF** [comment]
My mistake. we should check this diode
![image](https://user-images.githubusercontent.com/4116383/139598198-67043c98-977a-4e36-bd2b-ea6b318ea5d6.png)

**Comment by rusefillc** [comment]
both 12v points measure +12 - both left side of diode from top pic and right side of capacitor

right side of inductor is a huge LOL: applying "voltage" mode DMM there TURNS ON STM32. and measures +5v

**Comment by rusefillc** [comment]
Adding solder on both sides of inductor has resolved this issue

this 0.4 is from Jan 2021 batch when JLC did not populate inductors
