### ISSUE TITLE
chip shortage: LINEAR VOLTAGE REGULATOR

### ISSUE THREAD

**Issue by rusefillc** [mck1117/proteus#107]
TLS115D0EJXUMA1  only available for huge MOQ, do we have alternatives?

**Comment by Qwerty-OFF** [comment]
TLS115B0EJXUMA1
Similar, but without PG output
![изображение](https://user-images.githubusercontent.com/4116383/142826472-ba07f0b3-7be4-4f0f-81c7-8f7e16788e4c.png)

**Comment by rusefillc** [comment]
thank you @Qwerty-OFF I've placed the order

![image](https://user-images.githubusercontent.com/48498823/142866055-b04f9c7a-fafe-4407-891b-0374330cdef2.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/143243894-83417d18-5ae5-4042-b332-b14b9e4de3cb.png)

**Comment by rusefillc** [comment]
hellen has a somewhat similar drama with https://www.mouser.com/ProductDetail/Texas-Instruments/LMR14020SSQDDAQ1?qs=sGAEpiMZZMsyYdr3R27aV1%2FsE%2F4eX1bpBt4%2FHWGByuc%3D

are those compatible or not?

**Comment by mck1117** [comment]
unfortunately not really related - TLS115 is for the sensor supplies, and Proteus ALSO has an LMR14020 for the main supply.

**Comment by rusefillc** [comment]
Mouser has shipped
I've also ordered 386 of TLS115D0EJXUMA1

**Comment by rusefillc** [comment]
See also https://github.com/andreika-git/hellen-one/issues/119

**Comment by rusefillc** [comment]
I have a pile of both TLS115  and LMR14020
