### ISSUE TITLE
April fab chip shortage

### ISSUE THREAD

**Issue by rusefillc** [mck1117/proteus#119]
![image](https://user-images.githubusercontent.com/48498823/162966138-ba6879dc-df5d-4db2-972a-ede27a2969e0.png)

**Comment by mck1117** [comment]
C75646

**Comment by rusefillc** [comment]
@mck1117 please review

![Produce_DanZhi SMT_Snapshot Top 2582135A_Y222 SMT0220412720214](https://user-images.githubusercontent.com/48498823/163238742-bd9c4780-a48d-43e2-92b8-a03d1ab0fb8f.png)
![Produce_DanZhi SMT_Original_Snapshot Top 2582135A_Y222 SMT0220412720214](https://user-images.githubusercontent.com/48498823/163238744-d66715c1-27d9-4ae9-b077-b7037fee1009.png)

**Comment by mck1117** [comment]
looks OK to me
