### ISSUE TITLE
At least one of the VR channels should be discrete vr

### ISSUE THREAD

**Issue by rusefillc** [mck1117/proteus#120]
LNG engine has VR crank and single tooth VR crank meaning 85ms drama

would be nice to avoid 85ms drama at least on one of Proteus VR channels

**Comment by mck1117** [comment]
we can, see resistor config straps on the first channel

**Comment by rusefillc** [comment]
Please not 0.7 ;)

**Comment by mck1117** [comment]
as in, it's been there for some time now, a user can install resistors to change max9924 mode

**Comment by rusefillc** [comment]
How does one configure for single tooth cam sensor?

**Comment by mck1117** [comment]
![image](https://user-images.githubusercontent.com/568254/163047614-0db7d71b-ddee-46cb-8423-2bf8503e4667.png)
