### ISSUE TITLE
U1207 74HC2G17GW chip shortage

### ISSUE THREAD

**Issue by rusefillc** [mck1117/proteus#122]
C94189 is 74HC2G17GW,125 no more
while US-based assembly is possible it's just too darn "expensive"

74HC2G17GV,125 different package is also not available for JLC assembly

would it be possible to protect SN74LVC2G17 externally with additional JLC-assembled parts?

**Comment by rusefillc** [comment]
See https://github.com/rusefi/proteus/issues/1
See https://github.com/rusefi/alphax-4chan/issues/49

**Comment by mck1117** [comment]
yeah, we can go to discrete diodes + buffer

**Comment by mck1117** [comment]
fixed in master, diodes already on BOM for analog inputs used to protect digital inputs

**Comment by rusefillc** [comment]
> fixed in master, diodes already on BOM for analog inputs used to protect digital inputs, switched to SOT-23-6 74lvc2g17 buffers

that would be proteus 0.8 one day right? Not part of 0.7?
