### ISSUE TITLE
SPI FOR SBC CHIP

### ISSUE THREAD

**Issue by texasgdp754** [mck1117/proteus#36]
Noticed in mcu schematic that miso and mosi are swapped on the stm32 pins for SBC.  
And SBC miso and sbc CSN are  connected to each other on hierarchal root sheet

**Comment by mck1117** [comment]
It would appear that you are correct! I haven't tried to interface over SPI yet, so this is good to know!

**Comment by mck1117** [comment]
corrected on v0.3
