### ISSUE TITLE
sealed USB part number?

### ISSUE THREAD

**Issue by rusefi** [mck1117/proteus#53]
What is the $10 part for USB connector with the sealed cap?

I believe it's not 5787834-1? https://github.com/mck1117/proteus/blob/master/export/v0.3/proteus_bom_mouser.csv mentions  5787834-1 in the same line with "if user wants USB in sealed conn" but I am confused what does 5787834-1 have to do with sealed?

**Comment by mck1117** [comment]
Sealed connector is UB-20PMFP-LC7002.
5787834-1 is the un-sealed alternative.

**Comment by rusefi** [comment]
.sch file updated with UB-20PMFP-LC7002

shall we update .csv file as well?
