### ISSUE TITLE
DRC / ERC

### ISSUE THREAD

**Issue by jharvey** [mck1117/proteus#56]
Several DRC and ERC errors reported. Many are "not" important, things KC wants a power flat to suppress the error things like that could be cleaned up. 
-- Pin connected to.... should have power flag
-- PB2 could use nettie to suppress the message
-- Track to close to pad can be suppressed by adding a net name to the pad and making the via use that net name. AKA you really have a connected net. 
-- components could be moved by like 5 mils to prevent courtyard overlap errors.

**Comment by mck1117** [comment]
DRC was done in 0.4
