### ISSUE TITLE
Prototyping area

### ISSUE THREAD

**Issue by rusefillc** [mck1117/proteus#65]
How would Proteus handle Miata NB2 MAF 1k pull-down - where would it be located?

I recall there are some sensors with 12v output?

Would this case justify at least some prototyping area? I believe we can make PCB a bit larger if needed

**Comment by rusefillc** [comment]
Looks like we have a lot of space on top and bottom inside the recommended case? 

![image](https://user-images.githubusercontent.com/48498823/91113558-e791fd80-e653-11ea-9c2d-c41aa1ae546d.png)

**Comment by mck1117** [comment]
closed for now, will consider as part of #67
