### ISSUE TITLE
Both DIR and DIS look the same on PCB viewer

### ISSUE THREAD

**Issue by rusefillc** [mck1117/proteus#66]
We have ETB1_PWM and ETB2_PWM but DIR and DIR, DIS and DIS

![image](https://user-images.githubusercontent.com/48498823/90983215-81fe1e00-e53a-11ea-851e-207a40837dd8.png)

**Comment by mck1117** [comment]
No idea why it does that, they all look the same on the schematic :shrug:

**Comment by mck1117** [comment]
Just ctrl-click a net to highlight it, then there's no problem.
