### ISSUE TITLE
Use Ferrari ECU case and connector

### ISSUE THREAD

**Issue by rusefillc** [mck1117/proteus#67]
06 2006 Volkswagen Passat 2.0L ECM ECU Engine Computer Module | 3C0 907 115 G case is available from China brand new. also used from junk yards.

crimped pigtails are available from junk yard.

would it be the simplest way to give amazing Proteus an amazing case?

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/92339187-df3db780-f082-11ea-81ac-2cf064be409e.png)

https://www.ebay.com/itm/154-pin-ECU-Connector-Bosch-Type-for-Patch-Harness-Audi-Volkswagen/333606651255

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/92342944-71988800-f090-11ea-99a7-622a4c4d56db.png)

**Comment by mck1117** [comment]
154 pins is a lot - maybe some other features could get added, like integrated dumb coil drivers (igbt)

**Comment by rusefillc** [comment]
is now a probability of Proteus moving in this direction?

I can make the PCB outline and card board test it in a few weeks unless we already have the outline?

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi_documentation/blob/master/oem_docs/cases/BS616%20New%20Harvard%20Cover.dwg could be the case

**Comment by rusefillc** [comment]
[
![20201005_185249](https://user-images.githubusercontent.com/48498823/95140133-224f8100-073c-11eb-9b2f-c754b3946b75.jpg)

![20201005_182618](https://user-images.githubusercontent.com/48498823/95140134-22e81780-073c-11eb-83fe-b3dec2f1ff8c.jpg)

**Comment by rusefillc** [comment]
board outline https://github.com/mck1117/proteus/pull/85

**Comment by mck1117** [comment]
https://github.com/mck1117/atlas
