### ISSUE TITLE
Drivers with diagnostics

### ISSUE THREAD

**Issue by rusefillc** [mck1117/proteus#68]
For a nicer user experience shall we use something with diagnostics?

We have TLE6240 drivers already

**Comment by rusefillc** [comment]
Is TLE8110ED the more modern version of TLE6240 ?

**Comment by mck1117** [comment]
TLE9104 is an interesting option: direct control, 4 channel, spi diag

**Comment by rusefillc** [comment]
TLE9104 is 3A per channel, sweet?

**Comment by mck1117** [comment]
This is going to be confusing with TLE9201 and TLE9104 on the same board. Those PN are too similar!

**Comment by rusefillc** [comment]
Is this more or less https://github.com/mck1117/atlas ?

**Comment by mck1117** [comment]
yeah this is an atlas problem
