### ISSUE TITLE
[0.4] unpopulated cap on PCB not on schematics

### ISSUE THREAD

**Issue by rusefillc** [mck1117/proteus#70]
![image](https://user-images.githubusercontent.com/48498823/93719895-8f1b2680-fb53-11ea-83fa-6644fe213144.png)

**Comment by mck1117** [comment]
Fixed in master, not going to change exports since it isn't doing any harm.  That cap was deleted from the schematic, but not removed from the layout, so it stuck around.  It's also not listed in the BOM, so no part was mounted.
