### ISSUE TITLE
too many sources of pinout

### ISSUE THREAD

**Issue by rusefillc** [mck1117/proteus#79]
we have https://github.com/mck1117/proteus/blob/master/readme_pinout.md which seems to show 0.2 pinout but not call it out?

https://github.com/mck1117/proteus/blob/master/readme_pinout.md should probably be pointing at https://github.com/rusefi/rusefi/wiki/Hardware-Proteus-Wiring-v03 so that we do not have https://github.com/mck1117/proteus vs https://github.com/rusefi/rusefi/wiki copy-pasting?

**Comment by mck1117** [comment]
fixed
