### ISSUE TITLE
JLC-installed buttons for reset/bootloader

### ISSUE THREAD

**Issue by rusefillc** [mck1117/proteus#86]
jlc has many TACTILE SWITCHES

what is current Proteus extended component count?

**Comment by OrchardPerformance** [comment]
Bad news is, it's likely to already be maxed out. 
(the good news is, there is no more bad news?)

**Comment by rusefillc** [comment]
offtopic: do we have an explicit list of extended parts currently used on Proteus?

**Comment by mck1117** [comment]
done long ago
