### ISSUE TITLE
VNLD5160 and BTS4175SGA and TLS115  no avilable at all

### ISSUE THREAD

**Issue by NoTwixD** [mck1117/proteus#93]
44 weeks on mouser 
![image](https://user-images.githubusercontent.com/79408200/108684954-d38c6300-74f3-11eb-8fc5-778234c9568e.png)
![image](https://user-images.githubusercontent.com/79408200/108684969-d8e9ad80-74f3-11eb-84a0-7adee8a2a949.png)

**Comment by NoTwixD** [comment]
VN7 series are only single channel in so-8 Package

**Comment by NoTwixD** [comment]
VNLD5090-E more expensive higher Drain current up to 13 A (yehh i know its overkill) lower On resistance 160>80mOhm its mean less heat ;)

**Comment by NoTwixD** [comment]
and one older VNS3NV04DP-E not plug and play

**Comment by NoTwixD** [comment]
same story with BTS4175SGA

**Comment by NoTwixD** [comment]
I belive the tls115 i last one realy missing part of proteus at the moment

**Comment by mck1117** [comment]
Yes, the 5090 is interchangeable with the 5160, and while it does dissipate less heat, the current limit is also higher (which you may or may not want).

BTS4175 is interchangeable with the BSP762 and ISP762.

**Comment by mck1117** [comment]
The world is having a silicon shortage right now, so this isn't really a Proteus issue.  It's just going to be a mess for a while.
