### ISSUE TITLE
would Proteus be happy with GD32F450ZGT6

### ISSUE THREAD

**Issue by rusefillc** [mck1117/proteus#94]
JLC has 5 in stock, what would happen if I order a batch? :)

![image](https://user-images.githubusercontent.com/48498823/112001168-15a9c400-8af5-11eb-8018-8e1ebd3e4d60.png)

**Comment by mck1117** [comment]
>  would Proteus be happy with GD32F450ZGT6

No. I do not think modifying ChibiOS to support the GD32F450 is a valuable use of our time.
