### ISSUE TITLE
JLC headphone jack

### ISSUE THREAD

**Issue by rusefillc** [mck1117/proteus#95]
![image](https://user-images.githubusercontent.com/48498823/114925865-a4acb200-9dfd-11eb-8ad9-5035c48cc3bc.png)

**Comment by rusefillc** [comment]
looks like not a single human has used the headset so far

**Comment by mck1117** [comment]
maybe remove it entirely?

**Comment by rusefillc** [comment]
What would be a benefit of removal?

**Comment by mck1117** [comment]
dunno, I guess it also isn't hurting anything having the footprint there.
