### ISSUE TITLE
changelog to mention which rev. has working audio jack

### ISSUE THREAD

**Issue by rusefillc** [mck1117/proteus#97]
Do we have a changelog? can we please have one? can we mention which revision has working audio jack?

**Comment by OrchardPerformance** [comment]
0.4 is the first to have the jack. 
IIRC there is a change log in the proteus repository. 

I don't think anyone has tested it yet

**Comment by rusefillc** [comment]
i guess next question is: where is the changelog? :) Right now I do not see any changelog whatsoever.

**Comment by rusefillc** [comment]
https://github.com/mck1117/proteus/commit/3fa1c5cdf3f9f8cf965c077da976db35eb5623f4
